IF OBJECT_ID('CUATROGDD2018.SP_GetHotelesPorID_IDRol') IS NOT NULL
    DROP PROCEDURE CUATROGDD2018.SP_GetHotelesPorID_IDRol
GO
CREATE PROCEDURE [CUATROGDD2018].[SP_GetHotelesPorID_IDRol]
	@idUsuario int,
	@idRol int
AS
BEGIN
	SELECT H.* FROM [CUATROGDD2018].[Hoteles] H
	INNER JOIN [CUATROGDD2018].[Usuario_X_Hotel_X_Rol] UHR ON UHR.id_Hotel=H.id_Hotel 
	WHERE UHR.id_usuario = @idUsuario
	ORDER BY H.nombre
END
GO
