IF OBJECT_ID('CUATROGDD2018.SP_GetAllRolesValidos') IS NOT NULL
    DROP PROCEDURE CUATROGDD2018.SP_GetAllRolesValidos
GO
CREATE PROCEDURE [CUATROGDD2018].[SP_GetAllRolesValidos]
AS
	SELECT * FROM CUATROGDD2018.Roles
	WHERE habilitado='True'
GO