IF OBJECT_ID('CUATROGDD2018.SP_RolesComboBox', 'P') IS NOT NULL
    DROP PROCEDURE CUATROGDD2018.SP_RolesComboBox
GO
CREATE PROCEDURE CUATROGDD2018.SP_RolesComboBox
AS
	SELECT id_rol, nombre from CUATROGDD2018.Roles
	WHERE nombre != 'GUEST' AND nombre != 'Administrador General'
GO
