using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FrbaHotel.Entidades
{
    class Paises
    {
        public List<string> listaPaises = new List<string>();

        public Paises()
        {
            listaPaises.Add("Argentina");
            listaPaises.Add("Afganistán");
            listaPaises.Add("Albania");
            listaPaises.Add("Alemania");
            listaPaises.Add("Andorra");
            listaPaises.Add("Angola");
            listaPaises.Add("Anguilla");
            listaPaises.Add("Antártida Argentina");
            listaPaises.Add("Antigua y Barbuda");
            listaPaises.Add("Antillas Holandesas");
            listaPaises.Add("Arabia Saudita");
            listaPaises.Add("Argelia");
            listaPaises.Add("Armenia");
            listaPaises.Add("Aruba");
            listaPaises.Add("Australia");
            listaPaises.Add("Austria");
            listaPaises.Add("Azerbaiján");
            listaPaises.Add("Bahamas");
            listaPaises.Add("Bahrain");
            listaPaises.Add("Bangladesh");
            listaPaises.Add("Barbados");
            listaPaises.Add("Bélgica");
            listaPaises.Add("Belice");
            listaPaises.Add("Benin");
            listaPaises.Add("Bhutan");
            listaPaises.Add("Bielorusia");
            listaPaises.Add("Bolivia");
            listaPaises.Add("Bosnia Herzegovina");
            listaPaises.Add("Botswana");
            listaPaises.Add("Brasil");
            listaPaises.Add("Brunei");
            listaPaises.Add("Bulgaria");
            listaPaises.Add("Burkina Faso");
            listaPaises.Add("Burundi");
            listaPaises.Add("Cabo Verde");
            listaPaises.Add("Camboya");
            listaPaises.Add("Camerún");
            listaPaises.Add("Canadá");
            listaPaises.Add("Chad");
            listaPaises.Add("Chile");
            listaPaises.Add("China");
            listaPaises.Add("Chipre");
            listaPaises.Add("Colombia");
            listaPaises.Add("Comoros");
            listaPaises.Add("Congo");
            listaPaises.Add("Corea del Norte");
            listaPaises.Add("Corea del Sur");
            listaPaises.Add("Costa de Marfil");
            listaPaises.Add("Costa Rica");
            listaPaises.Add("Croacia");
            listaPaises.Add("Cuba");
            listaPaises.Add("Darussalam");
            listaPaises.Add("Dinamarca");
            listaPaises.Add("Djibouti");
            listaPaises.Add("Dominica");
            listaPaises.Add("Ecuador");
            listaPaises.Add("Egipto");
            listaPaises.Add("El Salvador");
            listaPaises.Add("Em. Arabes Un.");
            listaPaises.Add("Eritrea");
            listaPaises.Add("Eslovaquia");
            listaPaises.Add("Eslovenia");
            listaPaises.Add("España");
            listaPaises.Add("Estados Unidos");
            listaPaises.Add("Estonia");
            listaPaises.Add("Etiopía");
            listaPaises.Add("Fiji");
            listaPaises.Add("Filipinas");
            listaPaises.Add("Finlandia");
            listaPaises.Add("Francia");
            listaPaises.Add("Gabón");
            listaPaises.Add("Gambia");
            listaPaises.Add("Georgia");
            listaPaises.Add("Ghana");
            listaPaises.Add("Gibraltar");
            listaPaises.Add("Grecia");
            listaPaises.Add("Grenada");
            listaPaises.Add("Groenlandia");
            listaPaises.Add("Guadalupe");
            listaPaises.Add("Guam");
            listaPaises.Add("Guatemala");
            listaPaises.Add("Guayana Francesa");
            listaPaises.Add("Guinea");
            listaPaises.Add("Guinea Ecuatorial");
            listaPaises.Add("Guinea-Bissau");
            listaPaises.Add("Guyana");
            listaPaises.Add("Haití");
            listaPaises.Add("Holanda");
            listaPaises.Add("Honduras");
            listaPaises.Add("Hong Kong");
            listaPaises.Add("Hungría");
            listaPaises.Add("India");
            listaPaises.Add("Indonesia");
            listaPaises.Add("Irak");
            listaPaises.Add("Irán");
            listaPaises.Add("Irlanda");
            listaPaises.Add("Islandia");
            listaPaises.Add("Islas Cayman");
            listaPaises.Add("Islas Cook");
            listaPaises.Add("Islas Faroe");
            listaPaises.Add("Islas Marianas del Norte");
            listaPaises.Add("Islas Marshall");
            listaPaises.Add("Islas Solomon");
            listaPaises.Add("Islas Turcas y Caicos");
            listaPaises.Add("Islas Vírgenes");
            listaPaises.Add("Islas Wallis y Futuna");
            listaPaises.Add("Israel");
            listaPaises.Add("Italia");
            listaPaises.Add("Jamaica");
            listaPaises.Add("Japón");
            listaPaises.Add("Jordania");
            listaPaises.Add("Kazajstán");
            listaPaises.Add("Kenya");
            listaPaises.Add("Kirguistán");
            listaPaises.Add("Kiribati");
            listaPaises.Add("Kuwait");
            listaPaises.Add("Laos");
            listaPaises.Add("Lesotho");
            listaPaises.Add("Letonia");
            listaPaises.Add("Líbano");
            listaPaises.Add("Liberia");
            listaPaises.Add("Libia");
            listaPaises.Add("Liechtenstein");
            listaPaises.Add("Lituania");
            listaPaises.Add("Luxemburgo");
            listaPaises.Add("Macao");
            listaPaises.Add("Macedonia");
            listaPaises.Add("Madagascar");
            listaPaises.Add("Malasia");
            listaPaises.Add("Malawi");
            listaPaises.Add("Mali");
            listaPaises.Add("Malta");
            listaPaises.Add("Marruecos");
            listaPaises.Add("Martinica");
            listaPaises.Add("Mauricio");
            listaPaises.Add("Mauritania");
            listaPaises.Add("Mayotte");
            listaPaises.Add("México");
            listaPaises.Add("Micronesia");
            listaPaises.Add("Moldova");
            listaPaises.Add("Mónaco");
            listaPaises.Add("Mongolia");
            listaPaises.Add("Montserrat");
            listaPaises.Add("Mozambique");
            listaPaises.Add("Myanmar");
            listaPaises.Add("Namibia");
            listaPaises.Add("Nauru");
            listaPaises.Add("Nepal");
            listaPaises.Add("Nicaragua");
            listaPaises.Add("Níger");
            listaPaises.Add("Nigeria");
            listaPaises.Add("Noruega");
            listaPaises.Add("Nueva Caledonia");
            listaPaises.Add("Nueva Zelandia");
            listaPaises.Add("Omán");
            listaPaises.Add("Pakistán");
            listaPaises.Add("Panamá");
            listaPaises.Add("Papua Nueva Guinea");
            listaPaises.Add("Paraguay");
            listaPaises.Add("Perú");
            listaPaises.Add("Pitcairn");
            listaPaises.Add("Polinesia Francesa");
            listaPaises.Add("Polonia");
            listaPaises.Add("Portugal");
            listaPaises.Add("Puerto Rico");
            listaPaises.Add("Qatar");
            listaPaises.Add("RD Congo");
            listaPaises.Add("Reino Unido");
            listaPaises.Add("República Centroafricana");
            listaPaises.Add("República Checa");
            listaPaises.Add("República Dominicana");
            listaPaises.Add("Reunión");
            listaPaises.Add("Rumania");
            listaPaises.Add("Rusia");
            listaPaises.Add("Rwanda");
            listaPaises.Add("Sahara Occidental");
            listaPaises.Add("Saint Pierre y Miquelon");
            listaPaises.Add("Samoa");
            listaPaises.Add("Samoa Americana");
            listaPaises.Add("San Cristóbal y Nevis");
            listaPaises.Add("San Marino");
            listaPaises.Add("Santa Elena");
            listaPaises.Add("Santa Lucía");
            listaPaises.Add("Sao Tomé y Príncipe");
            listaPaises.Add("Senegal");
            listaPaises.Add("Serbia y Montenegro");
            listaPaises.Add("Seychelles");
            listaPaises.Add("Sierra Leona");
            listaPaises.Add("Singapur");
            listaPaises.Add("Siria");
            listaPaises.Add("Somalia");
            listaPaises.Add("Sri Lanka");
            listaPaises.Add("Sudáfrica");
            listaPaises.Add("Sudán");
            listaPaises.Add("Suecia");
            listaPaises.Add("Suiza");
            listaPaises.Add("Suriname");
            listaPaises.Add("Swazilandia");
            listaPaises.Add("Taiwán");
            listaPaises.Add("Uruguay");
          
        }

        public List<string> getAll(){
            
          return listaPaises;
        }
    }
}
