IF OBJECT_ID('CUATROGDD2018.SP_GetAllConsumibles') IS NOT NULL
    DROP PROCEDURE CUATROGDD2018.SP_GetAllConsumibles
GO
CREATE PROCEDURE CUATROGDD2018.SP_GetAllConsumibles  
AS
BEGIN
	SELECT * FROM [CUATROGDD2018].[Consumibles]
END
GO