IF OBJECT_ID('CUATROGDD2018.SP_GetAllMediosDePagos') IS NOT NULL
    DROP PROCEDURE CUATROGDD2018.SP_GetAllMediosDePagos
GO

CREATE PROCEDURE [CUATROGDD2018].[SP_GetAllMediosDePagos] 
AS
Begin
	SELECT * FROM [CUATROGDD2018].[Forma_de_Pago]
End
GO